# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-01-27 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'الطلاب', 'verbose_name_plural': 'الطلاب'},
        ),
    ]
