# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-02-08 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0003_auto_20220128_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'الاشخاص', 'verbose_name_plural': 'الاشخاص'},
        ),
        migrations.AlterModelOptions(
            name='usertype',
            options={'verbose_name': 'دور الفرد', 'verbose_name_plural': 'دور الفرد'},
        ),
        migrations.RemoveField(
            model_name='result',
            name='level',
        ),
    ]
